import { MigrationInterface, QueryRunner } from 'typeorm';

export class Todo1645728476065 implements MigrationInterface {
  name = 'Todo1645728476065';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "todo" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" text NOT NULL, "completed" boolean NOT NULL, "sort" integer NOT NULL, CONSTRAINT "PK_d429b7114371f6a35c5cb4776a7" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "todo"`);
  }
}
